version: '3.1'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./lovelace:/config/www/paddy/ha-electricity-schedule-card
      - ha_config:/config
    environment:
      - TZ=Europe/London
    ports:
      - "8123:8123"
    restart: unless-stopped

volumes:
  ha_config:
